wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.12
    start_time: 1694471805.970967
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.14.0
      6: 4.31.0
      8:
      - 5
backbone:
  desc: null
  value: resnet18
input_channels:
  desc: null
  value: 1
num_classes:
  desc: null
  value: 10
