wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: valid_loss_epoch
      5: 1
      6:
      - 1
    - 1: valid_acc_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1694474910.609909
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.14.0
      6: 4.31.0
      8:
      - 5
backbone:
  desc: null
  value: resnet18
input_channels:
  desc: null
  value: 1
num_classes:
  desc: null
  value: 10
